### PR TITLE
Release v2.1.0

### PR DESCRIPTION
**Pull request by Niko-r**

### CODE REVIEW

**Comment by bobTheBot-teads** [comment]
#### Automatic PR build trigger aborted:
`github-webhook` failed to determine if this pull request is mergeable after 10 retries.

Please trigger the build manually using `retest` in a few seconds.

**Comment by Niko-r** [comment]
retest

**Comment by bobTheBot-teads** [comment]
#### Automatic PR build trigger aborted:
`github-webhook` failed to determine if this pull request is mergeable after 10 retries.

Please trigger the build manually using `retest` in a few seconds.

**Comment by Niko-r** [comment]
retest

**Pull request merged**
