### PR TITLE
Update demo app with SDK V2

### PR DESCRIPTION
**Pull request by Niko-r**

### CODE REVIEW

**Comment by HugoGresse** [comment]
retest

**Comment by ibrahimennafaa** [comment]
retest

**Comment by ibrahimennafaa** [comment]
retest

**Comment by Niko-r** [comment]
retest

**Comment by HugoGresse** [comment]
retest

**Comment by Niko-r** [comment]
retest

**Comment by Niko-r** [comment]
retest

**Comment by Niko-r** [comment]
restest

**Comment by Niko-r** [comment]
retest

**Comment by gbougeard** [comment]
retest (just checking if the `mergeable` is well set)

**Comment by gbougeard** [comment]
retest

**Comment by pdalpra** [comment]
retest

**Pull request merged**
